export const ANIMATION_DURATION_AFTER_TYPING = 3150
export const DELAY_AFTER_ANIMATION_END = 700
export const BUTTON_ANIMATION_DURATION = 500
export const BUTTON_FIRST_RENDER_DELAY = 200
export const TOTAL_DELAY =
  ANIMATION_DURATION_AFTER_TYPING +
  DELAY_AFTER_ANIMATION_END +
  BUTTON_ANIMATION_DURATION +
  BUTTON_FIRST_RENDER_DELAY